/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTables;

import hashTables.TreeIntersection.TreeIntersection;
import hashTables.TreeIntersection.TreeNode;
import org.junit.jupiter.api.Test;

import java.util.HashMap;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

  @Test public void testHashTableAddingKeyValue() {
    hashTable<String, Integer> test = new hashTable<>();
    test.add("mahmoud",1);
    boolean output = test.contains("mahmoud");
    assertTrue(output);
  }

  @Test public void testHashTableRetrievingValueBasedOnKey() {
    hashTable<String, Integer> test = new hashTable<>();
    test.add("mahmoud",3);
    int output = test.get("mahmoud");
    assertEquals(3, output);
  }

  @Test public void testHashTableRetrievingNullForNotExistKey() {
    hashTable<String, Integer> test = new hashTable<>();
    test.add("deyaa",3);
    assertEquals(null, test.get("Fadi"));
  }

  @Test public void testHashTableHandleTheCollision() {
    hashTable<String, Integer> test = new hashTable<>();
    test.add("Hi", 50);
    test.add("My", 60);
    test.add("Name", 70);
    test.add("Mahmoud", 90);

    assertTrue(test.contains("Name"));
    assertTrue(test.contains("Mahmoud"));
    assertEquals(70, test.get("Name"));
    assertEquals(90, test.get("Mahmoud"));
  }

  @Test public void testHashTableRetrieveValueFromBucketHasCollision() {
    hashTable<String, Integer> test = new hashTable<>();
    test.add("Hi", 50);
    test.add("My", 60);
    test.add("Name", 70);
    test.add("Mahmoud", 90);

    assertTrue(test.contains("Name"));
    assertTrue(test.contains("Mahmoud"));
    assertEquals(70, test.get("Name"));
    assertEquals(90, test.get("Mahmoud"));
    int output1 = test.get("Name");
    int output2 = test.get("Mahmoud");
    assertEquals(90, output2);
    assertEquals(70, output1);

  }

  @Test void RepeatedWordTest() {
    hashTable repeatedWordTest = new hashTable();
    String test1="It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
    String test2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
    String test3 = "";
    String test4="Once upon a time, there was A brave princess who...";
    assertEquals("summer",repeatedWordTest.firstRepeatedWord(test1));
    assertEquals("it",repeatedWordTest.firstRepeatedWord(test2));
    assertEquals("there is no repeated word",repeatedWordTest.firstRepeatedWord(test3));
    assertEquals("a",repeatedWordTest.firstRepeatedWord(test4));
  }

  @Test
  public void LeftJoinTest() {
    HashMap hashMap1 = new HashMap();
    HashMap hashMap2 = new HashMap();

    hashMap1.put("fond", "enamored");
    hashMap1.put("wrath", "anger");
    hashMap1.put("diligent", "employed");
    hashMap1.put("outfit", "garb");
    hashMap1.put("guide", "usher");
    hashMap2.put("fond", "averse");
    hashMap2.put("wrath", "delight");
    hashMap2.put("diligent", "idle");
    hashMap2.put("guide", "follow");
    hashMap2.put("flow", "jam");

    hashTable leftJoin = new hashTable();
    String expOutput = "[{diligent: employed, idle}, {outfit: garb, null}, {wrath: anger, delight}, {guide: usher, follow}, {fond: enamored, averse}]";
    String ActOutput = leftJoin.leftJoin(hashMap1 , hashMap2).toString()
    assertEquals( expOutput ,ActOutput );
  }

}
