/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {

  //this is the main function.
  public static void main(String[] args) {
    LinkedList<Integer> insertList = new LinkedList<>();
    insertList.insert(1);
    insertList.insert(2);
    insertList.insert(3);
    insertList.insert(4);
    System.out.println(insertList);
    printLinkedListValues(insertList);
  }

  public static void printValues(LinkedList insertList){
    Node current=insertList.head;
    while (current != null) {
      System.out.println(current.value);
      current = current.next;
    }

  }
}
