/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

  @Test
  void InstantiateAnEmptyTreeTest() {
    BinarySearchTree<Integer> EmptyTree = new BinarySearchTree<>();
    assertNotNull(EmptyTree);
  }

  @Test
  void InstantiateTreeWithSingleRoot() {
    BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<>();
    binarySearchTree.add(1);
    assertEquals(1, binarySearchTree.str.getValue());
  }

  @Test
  void LeftAndRightChildToSingleRoot() {
    BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<>();
    binarySearchTree.add(1);
    binarySearchTree.add(2);
    binarySearchTree.add(3);
    assertEquals(1, binarySearchTree.str.getValue());
    assertEquals(2, binarySearchTree.str.getLeft().getValue());
    assertEquals(3, binarySearchTree.str.getRight().getValue());
  }




}
