/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

  @Test void graphTest1() {
    Graph graph = new Graph();
    Node n1 = new Node("A");
    Node n2 = new Node("B");
    Node n3 = new Node("C");
    Node n4 = new Node("D");
    assertEquals("[]", graph.graphList.toString());
    graph.addNode(n1);
    assertTrue(graph.graphList.contains(n1));
  }

  @Test void graphTest2() {
    Graph graph = new Graph();
    Node n1 = new Node("A");
    Node n2 = new Node("B");
    Node n3 = new Node("C");
    Node n4 = new Node("D");
    assertEquals("[]", graph.graphList.toString());
    graph.addNode(n2);
    assertTrue(graph.graphList.contains(n2));
  }

  @Test void graphTest3() {
    Graph graph = new Graph();
    Node n1 = new Node("A");
    Node n2 = new Node("B");
    Node n3 = new Node("C");
    Node n4 = new Node("D");
    assertEquals("[]", graph.graphList.toString());
    graph.addNode(n1);
    graph.addNode(n2);
    graph.addNode(n3);
    graph.addNode(n4);

    assertEquals("[A, B, C, D]", graph.toString());
  }

  @Test void graphTest4() {
    Graph graph = new Graph();
    Node n1 = new Node("A");
    Node n2 = new Node("B");
    Node n3 = new Node("C");
    Node n4 = new Node("D");
    assertEquals("[]", graph.graphList.toString());
    graph.addNode(n1);
    graph.addNode(n2);
    graph.addNode(n3);
    graph.addNode(n4);

    assertEquals("[A, B, C, D]", graph.toString());

  }
  }

